# Generated by Django 5.0.6 on 2024-05-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'db_table': 'alumnos',
            },
        ),
        migrations.RemoveField(
            model_name='mercaderia',
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Deposito',
        ),
        migrations.AlterUniqueTogether(
            name='mercaderia',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Mercaderia',
        ),
    ]
