# Generated by Django 5.0.6 on 2024-05-28 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0002_alumno_remove_mercaderia_categoria_delete_deposito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=20)),
                ('encargado', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'depositos',
            },
        ),
        migrations.CreateModel(
            name='Mercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=80)),
                ('prec_compra', models.IntegerField()),
                ('prec_venta', models.IntegerField()),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appStock.categoria')),
            ],
            options={
                'db_table': 'mercaderias',
                'unique_together': {('id', 'codigo')},
            },
        ),
    ]
