# Generated by Django 5.0.6 on 2024-05-28 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0003_categoria_deposito_mercaderia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
