# Generated by Django 5.0.6 on 2024-05-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0004_delete_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=20)),
                ('encargado', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'alumnos',
            },
        ),
    ]
