# Generated by Django 5.0.6 on 2024-05-28 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0005_alumno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
