# Generated by Django 5.0.6 on 2024-05-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0008_curso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Secciones',
        ),
    ]
