# Generated by Django 5.0.6 on 2024-05-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0009_rename_curso_secciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Secciones',
            new_name='Curso',
        ),
    ]
