# Generated by Django 5.0.6 on 2024-05-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0010_rename_secciones_curso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
