# Generated by Django 5.0.6 on 2024-06-18 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0013_asignatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mercaderia',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appStock.profesor'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appStock.profesor'),
        ),
        migrations.AlterModelTable(
            name='asignatura',
            table='asignaturas',
        ),
        migrations.AlterModelTable(
            name='curso',
            table='cursos',
        ),
        migrations.AlterModelTable(
            name='profesor',
            table='profesores',
        ),
    ]
