# Generated by Django 5.0.6 on 2024-06-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0014_rename_categoria_mercaderia_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('profesor', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'horarios',
            },
        ),
    ]
