# Generated by Django 5.0.6 on 2024-06-18 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0015_horario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
