# Generated by Django 5.0.6 on 2024-06-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0018_alter_asignatura_profesor_alter_curso_profesor_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asignatura',
            table='asignaturas',
        ),
    ]
