# Generated by Django 5.0.6 on 2024-06-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0020_alter_curso_table_alter_profesor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('presente', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'asistencias',
            },
        ),
    ]
