# Generated by Django 5.0.6 on 2024-06-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStock', '0021_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'calificaciones',
            },
        ),
    ]
